### ISSUE TITLE
628A and 83_84 epiccc slices cannot compile: no epiccc platform headers, no gate

### ISSUE THREAD

**Issue by apojomovsky** [apojomovsky/epic-hal#257]
## Background

`epic-common/manifest/modules.toml` declares `epiccc_sources` slices for PIC16F628A and PIC16F83_84, but neither family tree has an `include/epiccc/` platform header. The epic-cc path swaps the include dir to `include/epiccc` and fails at the first family umbrella include:

```
pic16f628a-hal/include/pic16f628a_hal.h:118:10: fatal error: 'pic16f628a_platform.h' file not found
```

Same shape for the 83_84 (`pic16f83_84_platform.h`). Verified on master, not introduced by #254: no CI epiccc-gate leg builds either family, so nothing catches it. Found while running #254's acceptance builds across every family that links the shared dispatch.

## Why it matters

The manifest declares conformant slices the epic-cc path cannot compile, and the families that link the shared dispatch on paper include two that never built on it. The next family author reading the manifest (or a ticket assuming "every shared-dispatch family builds") gets silently wrong ground truth.

## Scope

- Add `include/epiccc/` platform headers for both families (the 818/819 epiccc platform header is the thin reference; the accessors the dispatch and wdt/sleep epiccc files need are the minimum).
- Decide the CI story: either add epiccc-gate legs for the 628A and 84A canonical parts, or add an audit (the config-key-audit shape) that fails when a family declares an `epiccc_sources` slice its epic-cc path cannot compile.
- State the hex footprints if built.

## Acceptance

- `make epiccc-build` succeeds for 16F628A and 16F84A, or the families' slices are removed with the reason stated in the manifest.
- Every family with an `epiccc_sources` slice is covered by a gate or an audit, so the next divergence fails CI instead of waiting for a ticket to trip over it.

**Comment by apojomovsky** [comment]
Claimed by `oh-my-pi@ideapad5` at 2026-09-22T16:58:35+00:00 via epic-tasks.

**Comment by apojomovsky** [comment]
In review via epic-tasks: https://github.com/apojomovsky/epic-hal/pull/269
